//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class CategoryMap : EntityTypeConfiguration<Category>
    {
        public CategoryMap()
        {                        
              this.HasKey(t => t.CategoryID);        
              this.ToTable("Categories");
              this.Property(t => t.CategoryID).HasColumnName("CategoryID");
              this.Property(t => t.CategoryName).HasColumnName("CategoryName").IsRequired().HasMaxLength(15);
              this.Property(t => t.Description).HasColumnName("Description");
              this.Property(t => t.Picture).HasColumnName("Picture");
         }
    }
}
