//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class CustomerMap : EntityTypeConfiguration<Customer>
    {
        public CustomerMap()
        {                        
              this.HasKey(t => t.CustomerID);        
              this.ToTable("Customers");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID").IsRequired().IsFixedLength().HasMaxLength(5);
              this.Property(t => t.CompanyName).HasColumnName("CompanyName").IsRequired().HasMaxLength(40);
              this.Property(t => t.ContactName).HasColumnName("ContactName").HasMaxLength(30);
              this.Property(t => t.ContactTitle).HasColumnName("ContactTitle").HasMaxLength(30);
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(60);
              this.Property(t => t.City).HasColumnName("City").HasMaxLength(15);
              this.Property(t => t.Region).HasColumnName("Region").HasMaxLength(15);
              this.Property(t => t.PostalCode).HasColumnName("PostalCode").HasMaxLength(10);
              this.Property(t => t.Country).HasColumnName("Country").HasMaxLength(15);
              this.Property(t => t.Phone).HasColumnName("Phone").HasMaxLength(24);
              this.Property(t => t.Fax).HasColumnName("Fax").HasMaxLength(24);
         }
    }
}
