//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class Order_DetailMap : EntityTypeConfiguration<OrderDetail>
    {
        public Order_DetailMap()
        {                        
              this.HasKey(t => new {t.OrderID, t.ProductID});        
              this.ToTable("Order Details");
              this.Property(t => t.OrderID).HasColumnName("OrderID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.ProductID).HasColumnName("ProductID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.UnitPrice).HasColumnName("UnitPrice");
              this.Property(t => t.Quantity).HasColumnName("Quantity");
              this.Property(t => t.Discount).HasColumnName("Discount");
              this.HasRequired(t => t.Order).WithMany(t => t.Order_Details).HasForeignKey(d => d.OrderID);
              this.HasRequired(t => t.Product).WithMany(t => t.Order_Details).HasForeignKey(d => d.ProductID);
         }
    }
}
