//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class Summary_of_Sales_by_QuarterMap : EntityTypeConfiguration<SummaryofSalesbyQuarter>
    {
        public Summary_of_Sales_by_QuarterMap()
        {                        
              this.HasKey(t => t.OrderID);        
              this.ToTable("Summary of Sales by Quarter", "NorthwindModelStoreContainer");
              this.Property(t => t.ShippedDate).HasColumnName("ShippedDate");
              this.Property(t => t.OrderID).HasColumnName("OrderID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.Subtotal).HasColumnName("Subtotal");
         }
    }
}
