//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class CustomerDemographicMap : EntityTypeConfiguration<CustomerDemographic>
    {
        public CustomerDemographicMap()
        {                        
              this.HasKey(t => t.CustomerTypeID);        
              this.ToTable("CustomerDemographics");
              this.Property(t => t.CustomerTypeID).HasColumnName("CustomerTypeID").IsRequired().IsFixedLength().HasMaxLength(10);
              this.Property(t => t.CustomerDesc).HasColumnName("CustomerDesc");
    			this.HasMany(t => t.Customers).WithMany(t => t.CustomerDemographics)
    				.Map(m => 
    				{
    					m.ToTable("CustomerCustomerDemo");
    					m.MapLeftKey("CustomerTypeID");
    					m.MapRightKey("CustomerID");
    				});
         }
    }
}
