//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class EmployeeMap : EntityTypeConfiguration<Employee>
    {
        public EmployeeMap()
        {                        
              this.HasKey(t => t.EmployeeID);        
              this.ToTable("Employees");
              this.Property(t => t.EmployeeID).HasColumnName("EmployeeID");
              this.Property(t => t.LastName).HasColumnName("LastName").IsRequired().HasMaxLength(20);
              this.Property(t => t.FirstName).HasColumnName("FirstName").IsRequired().HasMaxLength(10);
              this.Property(t => t.Title).HasColumnName("Title").HasMaxLength(30);
              this.Property(t => t.TitleOfCourtesy).HasColumnName("TitleOfCourtesy").HasMaxLength(25);
              this.Property(t => t.BirthDate).HasColumnName("BirthDate");
              this.Property(t => t.HireDate).HasColumnName("HireDate");
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(60);
              this.Property(t => t.City).HasColumnName("City").HasMaxLength(15);
              this.Property(t => t.Region).HasColumnName("Region").HasMaxLength(15);
              this.Property(t => t.PostalCode).HasColumnName("PostalCode").HasMaxLength(10);
              this.Property(t => t.Country).HasColumnName("Country").HasMaxLength(15);
              this.Property(t => t.HomePhone).HasColumnName("HomePhone").HasMaxLength(24);
              this.Property(t => t.Extension).HasColumnName("Extension").HasMaxLength(4);
              this.Property(t => t.Photo).HasColumnName("Photo");
              this.Property(t => t.Notes).HasColumnName("Notes");
              this.Property(t => t.ReportsTo).HasColumnName("ReportsTo");
              this.Property(t => t.PhotoPath).HasColumnName("PhotoPath").HasMaxLength(255);
              this.HasOptional(t => t.Employee1).WithMany(t => t.Employees1).HasForeignKey(d => d.ReportsTo);
    			this.HasMany(t => t.Territories).WithMany(t => t.Employees)
    				.Map(m => 
    				{
    					m.ToTable("EmployeeTerritories");
    					m.MapLeftKey("EmployeeID");
    					m.MapRightKey("TerritoryID");
    				});
         }
    }
}
