//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class OrderMap : EntityTypeConfiguration<Order>
    {
        public OrderMap()
        {                        
              this.HasKey(t => t.OrderID);        
              this.ToTable("Orders");
              this.Property(t => t.OrderID).HasColumnName("OrderID");
              this.Property(t => t.CustomerID).HasColumnName("CustomerID").IsFixedLength().HasMaxLength(5);
              this.Property(t => t.EmployeeID).HasColumnName("EmployeeID");
              this.Property(t => t.OrderDate).HasColumnName("OrderDate");
              this.Property(t => t.RequiredDate).HasColumnName("RequiredDate");
              this.Property(t => t.ShippedDate).HasColumnName("ShippedDate");
              this.Property(t => t.ShipVia).HasColumnName("ShipVia");
              this.Property(t => t.Freight).HasColumnName("Freight");
              this.Property(t => t.ShipName).HasColumnName("ShipName").HasMaxLength(40);
              this.Property(t => t.ShipAddress).HasColumnName("ShipAddress").HasMaxLength(60);
              this.Property(t => t.ShipCity).HasColumnName("ShipCity").HasMaxLength(15);
              this.Property(t => t.ShipRegion).HasColumnName("ShipRegion").HasMaxLength(15);
              this.Property(t => t.ShipPostalCode).HasColumnName("ShipPostalCode").HasMaxLength(10);
              this.Property(t => t.ShipCountry).HasColumnName("ShipCountry").HasMaxLength(15);
              this.HasOptional(t => t.Customer).WithMany(t => t.Orders).HasForeignKey(d => d.CustomerID);
              this.HasOptional(t => t.Employee).WithMany(t => t.Orders).HasForeignKey(d => d.EmployeeID);
              this.HasOptional(t => t.Shipper).WithMany(t => t.Orders).HasForeignKey(d => d.ShipVia);
         }
    }
}
