//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data.Repository.Mappings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Northwind.Core;
    
    public partial class ShipperMap : EntityTypeConfiguration<Shipper>
    {
        public ShipperMap()
        {                        
              this.HasKey(t => t.ShipperID);        
              this.ToTable("Shippers");
              this.Property(t => t.ShipperID).HasColumnName("ShipperID");
              this.Property(t => t.CompanyName).HasColumnName("CompanyName").IsRequired().HasMaxLength(40);
              this.Property(t => t.Phone).HasColumnName("Phone").HasMaxLength(24);
         }
    }
}
